## Array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

# NumPy

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python



In [2]:
# if you have installed python manually, uncomment the line below to use numpy
# after installing you need to comment the code again

# pip install numpy

# or in Anaconda environment use the command below, don't forget to comment the code again

# conda install numpy

In [1]:
import numpy as np

In [ ]:
# We should learn how to create an array and a multidimentional array
# starting with a simple array

my_lst = [1, 2, 3, 4, 5]

arr = np.array(my_lst)
arr
# The output of the arr has one bracket at the begining and one at the end
# this was a one dimentional array

array([1, 2, 3, 4, 5])

In [8]:
print(arr)
print(type(arr))
print(arr.shape)
# .shape is an attribute of the array that shows the shape of the array
# if it is a one dimentional array, it will show the number of elements in the array
# if it is a two dimentional array, it will show the number of rows and columns
# if it is a three dimentional array, it will show the number of rows, columns and depth

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [13]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [6, 7, 8, 9, 10]
lst3 = [11, 12, 13, 14, 15]

arr = np.array([lst1, lst2, lst3])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr.shape

(3, 5)

* in most of the data analysis and data exploratory part, we deal with two dimentional arrays with a lot of fearures (columns) and a lot of rows (data points)

In [15]:
# reshaping the array
arr.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
arr.reshape(1, 15)
# in reshaping the array, the number of elements in the reshaped array should be 
# equal to the number of elements in the original array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
arr.shape

(3, 5)

In [20]:
new_arr = arr.reshape(5,3)
new_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [21]:
new_arr.shape

(5, 3)

# Indexing

always retrieving data inside each data structure is very important.